server:
  port: 8080
spring:
  application:
    name: cafeflow
  
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  temporal:
    connection:
      target: localhost:7233
#     workers:
#       - name: "REDDIT_WORKER"
#         task-queue: "REDDIT_WORKER"
#         capacity:
#           max-concurrent-workflow-task-pollers: 2
#         workflow-classes:
#           - com.cafeflow.workflows.reddit.RedditAutomationWorkflowImpl
#         activity-beans:
#           - redditActivitiesImpl

logging:
  level:
    io.temporal: INFO
    com.cafeflow: DEBUG

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}

twitter:
  api:
    bearer-token: ${X_BEARER_TOKEN:}
    api-key: ${X_API_KEY:}
    api-secret: ${X_API_SECRET:}

google:
  drive:
    application-name: ${GD_APP_NAME:CafeFlow}
    credentials-path: ${GD_CREDENTIALS_PATH:/credentials.json}
    tokens-directory: ${GD_TOKENS_DIR:tokens}

llm:
  default-provider: ${LLM_DEFAULT_PROVIDER:gemini}
  gemini:
    api-key: ${GEMINI_API_KEY:}
    model: ${GEMINI_MODEL:gemini-2.0-flash}
  groq:
    api-key: ${GROQ_API_KEY:}
    model: ${GROQ_MODEL:llama-3.3-70b-versatile}
